// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: USBprotocol.proto

package com.idemia.USBProtocol;

public final class USBProtocolProtos {
  private USBProtocolProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface USBCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:USBProtocol.USBCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>bytes parameters = 2;</code>
     */
    com.google.protobuf.ByteString getParameters();
  }
  /**
   * Protobuf type {@code USBProtocol.USBCommand}
   */
  public  static final class USBCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:USBProtocol.USBCommand)
      USBCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use USBCommand.newBuilder() to construct.
    private USBCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private USBCommand() {
      id_ = 0;
      parameters_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private USBCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {

              parameters_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.idemia.USBProtocol.USBProtocolProtos.USBCommand.class, com.idemia.USBProtocol.USBProtocolProtos.USBCommand.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PARAMETERS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString parameters_;
    /**
     * <code>bytes parameters = 2;</code>
     */
    public com.google.protobuf.ByteString getParameters() {
      return parameters_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!parameters_.isEmpty()) {
        output.writeBytes(2, parameters_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!parameters_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, parameters_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.idemia.USBProtocol.USBProtocolProtos.USBCommand)) {
        return super.equals(obj);
      }
      com.idemia.USBProtocol.USBProtocolProtos.USBCommand other = (com.idemia.USBProtocol.USBProtocolProtos.USBCommand) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getParameters()
          .equals(other.getParameters());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParameters().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.idemia.USBProtocol.USBProtocolProtos.USBCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code USBProtocol.USBCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:USBProtocol.USBCommand)
        com.idemia.USBProtocol.USBProtocolProtos.USBCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.idemia.USBProtocol.USBProtocolProtos.USBCommand.class, com.idemia.USBProtocol.USBProtocolProtos.USBCommand.Builder.class);
      }

      // Construct using com.idemia.USBProtocol.USBProtocolProtos.USBCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        parameters_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBCommand_descriptor;
      }

      public com.idemia.USBProtocol.USBProtocolProtos.USBCommand getDefaultInstanceForType() {
        return com.idemia.USBProtocol.USBProtocolProtos.USBCommand.getDefaultInstance();
      }

      public com.idemia.USBProtocol.USBProtocolProtos.USBCommand build() {
        com.idemia.USBProtocol.USBProtocolProtos.USBCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.idemia.USBProtocol.USBProtocolProtos.USBCommand buildPartial() {
        com.idemia.USBProtocol.USBProtocolProtos.USBCommand result = new com.idemia.USBProtocol.USBProtocolProtos.USBCommand(this);
        result.id_ = id_;
        result.parameters_ = parameters_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idemia.USBProtocol.USBProtocolProtos.USBCommand) {
          return mergeFrom((com.idemia.USBProtocol.USBProtocolProtos.USBCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.idemia.USBProtocol.USBProtocolProtos.USBCommand other) {
        if (other == com.idemia.USBProtocol.USBProtocolProtos.USBCommand.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getParameters() != com.google.protobuf.ByteString.EMPTY) {
          setParameters(other.getParameters());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.idemia.USBProtocol.USBProtocolProtos.USBCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.idemia.USBProtocol.USBProtocolProtos.USBCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString parameters_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes parameters = 2;</code>
       */
      public com.google.protobuf.ByteString getParameters() {
        return parameters_;
      }
      /**
       * <code>bytes parameters = 2;</code>
       */
      public Builder setParameters(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parameters_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes parameters = 2;</code>
       */
      public Builder clearParameters() {
        
        parameters_ = getDefaultInstance().getParameters();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:USBProtocol.USBCommand)
    }

    // @@protoc_insertion_point(class_scope:USBProtocol.USBCommand)
    private static final com.idemia.USBProtocol.USBProtocolProtos.USBCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.idemia.USBProtocol.USBProtocolProtos.USBCommand();
    }

    public static com.idemia.USBProtocol.USBProtocolProtos.USBCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<USBCommand>
        PARSER = new com.google.protobuf.AbstractParser<USBCommand>() {
      public USBCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new USBCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<USBCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<USBCommand> getParserForType() {
      return PARSER;
    }

    public com.idemia.USBProtocol.USBProtocolProtos.USBCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface USBResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:USBProtocol.USBResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 status = 2;</code>
     */
    int getStatus();

    /**
     * <code>bytes parameters = 3;</code>
     */
    com.google.protobuf.ByteString getParameters();
  }
  /**
   * Protobuf type {@code USBProtocol.USBResponse}
   */
  public  static final class USBResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:USBProtocol.USBResponse)
      USBResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use USBResponse.newBuilder() to construct.
    private USBResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private USBResponse() {
      id_ = 0;
      status_ = 0;
      parameters_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private USBResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              status_ = input.readInt32();
              break;
            }
            case 26: {

              parameters_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.idemia.USBProtocol.USBProtocolProtos.USBResponse.class, com.idemia.USBProtocol.USBProtocolProtos.USBResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>int32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int PARAMETERS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString parameters_;
    /**
     * <code>bytes parameters = 3;</code>
     */
    public com.google.protobuf.ByteString getParameters() {
      return parameters_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (status_ != 0) {
        output.writeInt32(2, status_);
      }
      if (!parameters_.isEmpty()) {
        output.writeBytes(3, parameters_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (!parameters_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, parameters_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.idemia.USBProtocol.USBProtocolProtos.USBResponse)) {
        return super.equals(obj);
      }
      com.idemia.USBProtocol.USBProtocolProtos.USBResponse other = (com.idemia.USBProtocol.USBProtocolProtos.USBResponse) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getStatus()
          == other.getStatus());
      result = result && getParameters()
          .equals(other.getParameters());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParameters().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.idemia.USBProtocol.USBProtocolProtos.USBResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code USBProtocol.USBResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:USBProtocol.USBResponse)
        com.idemia.USBProtocol.USBProtocolProtos.USBResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.idemia.USBProtocol.USBProtocolProtos.USBResponse.class, com.idemia.USBProtocol.USBProtocolProtos.USBResponse.Builder.class);
      }

      // Construct using com.idemia.USBProtocol.USBProtocolProtos.USBResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        status_ = 0;

        parameters_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idemia.USBProtocol.USBProtocolProtos.internal_static_USBProtocol_USBResponse_descriptor;
      }

      public com.idemia.USBProtocol.USBProtocolProtos.USBResponse getDefaultInstanceForType() {
        return com.idemia.USBProtocol.USBProtocolProtos.USBResponse.getDefaultInstance();
      }

      public com.idemia.USBProtocol.USBProtocolProtos.USBResponse build() {
        com.idemia.USBProtocol.USBProtocolProtos.USBResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.idemia.USBProtocol.USBProtocolProtos.USBResponse buildPartial() {
        com.idemia.USBProtocol.USBProtocolProtos.USBResponse result = new com.idemia.USBProtocol.USBProtocolProtos.USBResponse(this);
        result.id_ = id_;
        result.status_ = status_;
        result.parameters_ = parameters_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idemia.USBProtocol.USBProtocolProtos.USBResponse) {
          return mergeFrom((com.idemia.USBProtocol.USBProtocolProtos.USBResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.idemia.USBProtocol.USBProtocolProtos.USBResponse other) {
        if (other == com.idemia.USBProtocol.USBProtocolProtos.USBResponse.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getParameters() != com.google.protobuf.ByteString.EMPTY) {
          setParameters(other.getParameters());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.idemia.USBProtocol.USBProtocolProtos.USBResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.idemia.USBProtocol.USBProtocolProtos.USBResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 2;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString parameters_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes parameters = 3;</code>
       */
      public com.google.protobuf.ByteString getParameters() {
        return parameters_;
      }
      /**
       * <code>bytes parameters = 3;</code>
       */
      public Builder setParameters(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parameters_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes parameters = 3;</code>
       */
      public Builder clearParameters() {
        
        parameters_ = getDefaultInstance().getParameters();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:USBProtocol.USBResponse)
    }

    // @@protoc_insertion_point(class_scope:USBProtocol.USBResponse)
    private static final com.idemia.USBProtocol.USBProtocolProtos.USBResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.idemia.USBProtocol.USBProtocolProtos.USBResponse();
    }

    public static com.idemia.USBProtocol.USBProtocolProtos.USBResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<USBResponse>
        PARSER = new com.google.protobuf.AbstractParser<USBResponse>() {
      public USBResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new USBResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<USBResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<USBResponse> getParserForType() {
      return PARSER;
    }

    public com.idemia.USBProtocol.USBProtocolProtos.USBResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_USBProtocol_USBCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_USBProtocol_USBCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_USBProtocol_USBResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_USBProtocol_USBResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021USBprotocol.proto\022\013USBProtocol\",\n\nUSBC" +
      "ommand\022\n\n\002id\030\001 \001(\005\022\022\n\nparameters\030\002 \001(\014\"=" +
      "\n\013USBResponse\022\n\n\002id\030\001 \001(\005\022\016\n\006status\030\002 \001(" +
      "\005\022\022\n\nparameters\030\003 \001(\014B+\n\026com.idemia.USBP" +
      "rotocolB\021USBProtocolProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_USBProtocol_USBCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_USBProtocol_USBCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_USBProtocol_USBCommand_descriptor,
        new java.lang.String[] { "Id", "Parameters", });
    internal_static_USBProtocol_USBResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_USBProtocol_USBResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_USBProtocol_USBResponse_descriptor,
        new java.lang.String[] { "Id", "Status", "Parameters", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
